### ISSUE TITLE
[BUG] Failed to load plugin | Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by crashzk** [johandrevwyk/ExtraUtilities#4]
Receiving this error log:
```
2024-05-13 22:21:41.382 -03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/clientes/OGP_User_Files/whmcs/8392/game/csgo/addons/counterstrikesharp/plugins/ExtraUtilities/ExtraUtilities.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Config version mismatch
   at ExtraUtilities.ExtraUtilities.OnConfigParsed(UtilitiesConfig config)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 392
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```

- ExtraUtilities Version: 0.1.5
- CSSharp Version: 233 (1.0.233+02d5191)
- Metamod Version: 2.0.0-dev+1291

Config`ExtraUtilities.json`:
```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'ExtraUtilities', at 2024/05/04 10:28:19
{
  "General": {
    "Webhook": "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "Bunnyhop": {
    "Enabled": true,
    "SpeedLimit": 320,
    "Threshold": 128,
    "DecreasePlayerSpeed": true
  },
  "SpinDetection": {
    "Enabled": true,
    "HeadshotPenetratedNoScope": 3,
    "HeadshotPenetrated": 10,
    "HeadshotSmokePenetratedNoScope": 3,
    "HeadshotSmoke": 8,
    "HeadshotSmokePenetrated": 5,
    "BanPlayer": true
  },
  "RapidFire": {
    "Enabled": true,
    "BanPlayer": true,
    "Threshold": 3
  },
  "BannedWordsSettings": {
    "Enabled": false,
	"SendWebhook": true,
    "SilencePlayer": true,
    "Duration": 4080
  },
  "BannedWords": [
    "word1",
    "word2"
  ],
  "ConfigVersion": 3
}
```

**Comment by crashzk** [comment]
I generated a new configuration file and for some reason it is not creating the `SendWebhook" key and `ConfigVersion` comes with version 2 as well.

```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'ExtraUtilities', at 2024/05/13 10:33:55
{
  "General": {
    "Webhook": "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "Bunnyhop": {
    "Enabled": true,
    "SpeedLimit": 320,
    "Threshold": 128,
    "DecreasePlayerSpeed": true
  },
  "SpinDetection": {
    "Enabled": true,
    "HeadshotPenetratedNoScope": 3,
    "HeadshotPenetrated": 10,
    "HeadshotSmokePenetratedNoScope": 3,
    "HeadshotSmoke": 8,
    "HeadshotSmokePenetrated": 5,
    "BanPlayer": true
  },
  "RapidFire": {
    "Enabled": true,
    "BanPlayer": true,
    "Threshold": 3
  },
  "BannedWordsSettings": {
    "Enabled": false,
    "SilencePlayer": true,
    "Duration": 4080
  },
  "BannedWords": [
    "word1",
    "word2"
  ],
  "ConfigVersion": 2
}
```

**Comment by crashzk** [comment]
I believe it could be a Realeases launch error.

Latest version 0.1.5: https://github.com/johandrevwyk/ExtraUtilities/releases/tag/0.1.5

However, his commit is from version 0.1.6.

**Comment by johandrevwyk** [comment]
released new version with latest commits, please delete config and let it regenerate then try again (:

**Comment by crashzk** [comment]
No errors now, test everything now and get back to me with anything, thank you!
